from .cfa_catering_message_project import cfa_catering_message_project
from .cfa_cem_message_project import cfa_cem_message_project
from .cfa_sales_message_project import cfa_sales_message_project
from .cfa_sales_log_all_year_project import cfa_sales_log_all_year_project