from .cfa_download_catering_route import cfa_download_catering_route
from .cfa_download_cems_route import cfa_download_cems_route
from .cfa_fullscale_report_route import cfa_fullscale_report_route
from .cfa_login_home_route import cfa_login_home_route
from .cfa_login_servicepoint_route import cfa_login_servicepoint_route
from .cfa_goto_daypart_activity_route import cfa_goto_daypart_activity_route
from .cfa_download_daypart_activity_route import cfa_download_daypart_activity_route
from .cfa_goto_time_detail_report_route import cfa_goto_time_detail_report_route
from .cfa_download_time_detail_report_route import cfa_download_time_detail_report_route

from .groupme_login_route import groupme_login_route
from .groupme_message_route import groupme_message_route

from .slack_login_route import slack_login_route
from .slack_message_route import slack_message_route

from .google_goto_sales_form_route import google_goto_sales_form_route
from .google_submit_sales_tracking_form_route import google_submit_sales_tracking_form_route
from .google_goto_cems_route import google_goto_cems_route
from .google_submit_cems_form_route import google_submit_cems_form_route